/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{ts,tsx,js,jsx}',
  ],
  safelist: [
    // Grid configurations
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'grid-cols-6',
    
    // Gaps
    'gap-1',
    'gap-1.5',
    'gap-2',
    'gap-3',
    'gap-4',
    'gap-6',
    
    // Padding
    'p-0.5',
    'p-1',
    'p-1.5',
    'p-2',
    'p-3',
    'p-4',
    'p-5',
    'p-6',
    'p-8',
    'p-12',
    'p-16',
    'p-20',
    'p-24',
    'pt-1',
    'pt-2',
    'pt-3',
    'pb-1',
    'pb-2',
    'pb-4',
    'pb-5',
    'pb-6',
    'pb-8',
    'px-2',
    'px-4',
    'px-6',
    'px-8',
    'px-12',
    'px-20',
    'px-24',
    'px-32',
    'py-2',
    'py-4',
    'py-6',
    'py-8',
    'py-10',
    'py-12',
    'py-16',
    'py-20',
    'py-24',
    
    // Text sizes - CRITICAL for buttons and cards
    'text-[7px]',
    'text-[8px]',
    'text-[9px]',
    'text-[10px]',
    'text-[11px]',
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'text-5xl',
    'text-6xl',
    'text-7xl',
    'text-8xl',
    'text-9xl',
    
    // Widths - CRITICAL for card sizes
    'w-12',
    'w-16',
    'w-20',
    'w-24',
    'w-28',
    'w-32',
    'w-36',
    'w-40',
    'w-48',
    'w-56',
    'w-64',
    'w-68',
    'w-72',
    'w-80',
    'w-96',
    'w-full',
    'w-[160px]',
    'w-[280px]',
    
    // Heights
    'h-8',
    'h-10',
    'h-12',
    'h-16',
    'h-20',
    'h-24',
    'h-32',
    'h-40',
    'h-48',
    'h-full',
    'h-[42px]',
    
    // Aspect ratios
    'aspect-square',
    'aspect-[4/3]',
    'aspect-[4/5]',
    
    // Max widths
    'max-w-[280px]',
    'max-w-[340px]',
    'max-w-sm',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-2xl',
    'max-w-4xl',
    'max-w-6xl',
    
    // Opacity
    'opacity-0',
    'opacity-50',
    'opacity-70',
    'opacity-80',
    'opacity-100',
    
    // Borders
    'border',
    'border-2',
    'border-3',
    'border-4',
    'border-8',
    'rounded',
    'rounded-lg',
    'rounded-xl',
    'rounded-2xl',
    'rounded-3xl',
    'rounded-[3rem]',
    'rounded-[4rem]',
    
    // Other utilities
    'grayscale',
    'cursor-pointer',
    'hover:scale-105',
    'hover:scale-110',
    'hover:opacity-100',
    'hover:shadow-cyan-500/50',
    'hover:shadow-yellow-500/50',
    'hover:border-purple-500',
    'hover:border-yellow-500',
    'transition-all',
    'leading-none',
    'leading-tight',
    'line-clamp-2',
    
    // Z-index
    'z-0',
    'z-10',
    'z-50',
    'z-[60]',
    'z-[100]',
    'z-[200]',
    
    // Specific card width that was causing massive cards
    'w-68',
  ],
  theme: {
    extend: {
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.75rem' }],
      },
      // Add w-68 to theme since it's not standard Tailwind
      spacing: {
        '68': '17rem',
      },
    },
  },
  plugins: [],
}